name: Deploy

on: 
  release: released

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          echo "$VERSION"